trustbloc/fabric-peer-ext

- .ci-properties
- .gitignore
- Makefile
- README.md
- extensions/go.mod
- extensions/main.go
- golangci.yml
- scripts/build_fabric.sh
- scripts/check_lint.sh
- scripts/check_version.sh
- scripts/dependencies.sh
- scripts/pull_fabric.sh
> [#1] Add build structure

- mod/peer/go.sum
- mod/peer/testutil/ext_test_env.go
> [#8] Setup couchdb for unit-test

- README.md
> [#30] Fix codebeat badge

- mod/peer/idstore/store.go
- mod/peer/idstore/store_test.go
> feat: Switch fabric/mod/idstore to use Couchdb

- .golangci.yml
- go.mod
- go.sum
- mod/peer/go.sum
- mod/peer/pvtdatastorage/store.go
- mod/peer/pvtdatastorage/store_test.go
- pkg/pvtdatastorage/cdbpvtdatastore/couchdb_conv.go
- pkg/pvtdatastorage/cdbpvtdatastore/store_impl.go
- pkg/pvtdatastorage/cdbpvtdatastore/store_impl_test.go
- pkg/pvtdatastorage/cdbpvtdatastore/test_exports.go
- pkg/pvtdatastorage/common/collelgproc.go
- pkg/pvtdatastorage/common/helper.go
- pkg/pvtdatastorage/common/kv_encoding.go
- pkg/pvtdatastorage/common/store.go
- pkg/pvtdatastorage/common/v11.go
> feat: Add CouchDB implementation for pvtdata storage

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/pvtdatastorage/cachedpvtdatastore/store_impl.go
- pkg/pvtdatastorage/cachedpvtdatastore/store_impl_test.go
- pkg/pvtdatastorage/cachedpvtdatastore/test_exports.go
- pkg/pvtdatastorage/cdbpvtdatastore/couchdb_conv.go
- pkg/pvtdatastorage/cdbpvtdatastore/store_impl.go
- pkg/pvtdatastorage/cdbpvtdatastore/store_impl_test.go
- pkg/pvtdatastorage/cdbpvtdatastore/test_exports.go
> feat: Add Cache implementation for pvtdata storage

- .ci-properties
> ci: Add fabric peer ext images tag

- .github/semantic.yml
- README.md
Closes #44
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
> ci: configure semantic-pull-requests to check commits

- Makefile
- scripts/check_license.sh
> ci: Add check license script

- mod/peer/pvtdatastorage/store.go
- pkg/pvtdatastorage/store_impl.go
- pkg/pvtdatastorage/store_impl_test.go
- pkg/pvtdatastorage/test_exports.go
> feat: Integrate pvtdata store cache impl with CouchDB impl

- pkg/collections/transientdata/storeprovider/store/api/api.go
- pkg/collections/transientdata/storeprovider/store/dbstore/dbstore.go
- pkg/collections/transientdata/storeprovider/store/dbstore/dbstore_provider.go
- pkg/collections/transientdata/storeprovider/store/dbstore/dbstore_test.go
- pkg/config/config.go
Implemented a LevelDB store for transient data
collections.
closes #52
> feat: Transient Data DB Store

- README.md
Closes #71
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
> docs: use common community guidelines

- pkg/blkstorage/cdbblkstorage/cdb_blkstorage.go
- pkg/blkstorage/cdbblkstorage/cdb_blkstorage_provider.go
- pkg/blkstorage/cdbblkstorage/cdb_blkstorage_provider_test.go
> feat: Role based features in couchdb block storage

- test/bddtests/bddtests_test.go
- test/bddtests/go.mod
- test/bddtests/go.sum
> test: Switch from fabric-peer-test-lib to fabric-peer-test-common

- mod/peer/collections/policy/validator.go
- mod/peer/collections/policy/validator_test.go
- pkg/collections/transientdata/policy/validator.go
- pkg/collections/transientdata/policy/validator_test.go
Implemented a policy validator for Transient Data collections.
closes #78
> feat: Transient Data Policy Validator

- scripts/dependencies.sh
> ci: Fix licence header in dependencies.sh

- test/bddtests/features/step_definitions/common_steps.js
- test/bddtests/features/transient_data.feature
Added BDD tests for transient data collections.
closes #89
> test: Transient Data Integration Tests

- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore.go
- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore_provider.go
- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore_test.go
- pkg/config/config.go
Added a Couch DB store for Off-Ledger collections.
closes #58
> feat: Couch DB Store for Off-Ledger Collections

- mod/peer/collections/dissemination/disseminationplan.go
- mod/peer/collections/dissemination/disseminationplan_test.go
- mod/peer/go.sum
- pkg/collections/offledger/dissemination/disseminationplan.go
- pkg/collections/offledger/dissemination/disseminator.go
- pkg/collections/offledger/dissemination/disseminator_test.go
- pkg/config/config.go
- pkg/config/config_test.go
Disseminates Off-Ledger data to other peers according to the collection
policy/config.
closes #62
> feat: Dissemination Plan for Off-Ledger Collections

- mod/peer/collections/policy/validator.go
- mod/peer/collections/policy/validator_test.go
- pkg/collections/offledger/policy/validator.go
- pkg/collections/offledger/policy/validator_test.go
Validate the collection config/policy for off-ledger collections.
closes #80
> feat: Off-Ledger Collection Policy Validator

- test/bddtests/bddtests_test.go
- test/bddtests/features/off_ledger.feature
- test/bddtests/features/step_definitions/offledger_steps.ts
- test/bddtests/fixtures/testdata/src/github.com/trustbloc/e2e_cc/e2e_cc.go
- test/bddtests/offledger_steps.go
Added BDD tests for off-ledger and DCAS collection types.
closes #90
> test: Add Off-Ledger and DCAS BDD tests

- pkg/collections/client/client.go
- pkg/collections/client/client_test.go
- pkg/collections/offledger/dcas/client/dcasclient_test.go
- pkg/collections/offledger/dissemination/disseminationplan.go
- pkg/collections/offledger/dissemination/disseminator_test.go
- pkg/collections/offledger/storeprovider/olstore.go
- pkg/collections/offledger/storeprovider/olstore_test.go
- pkg/collections/offledger/storeprovider/olstoreprovider.go
- pkg/collections/offledger/storeprovider/olstoreprovider_test.go
- pkg/collections/offledger/storeprovider/store/cache/cache.go
- pkg/collections/offledger/storeprovider/store/cache/cache_test.go
- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore.go
- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore_test.go
- pkg/collections/offledger/storeprovider/store/leveldbstore/dbstore.go
- pkg/collections/offledger/storeprovider/store/leveldbstore/dbstore_test.go
- pkg/collections/storeprovider/storeprovider.go
- test/bddtests/features/off_ledger.feature
Added ability to delete DCAS and off-ledger data.
closes #135
> feat: Delete Off-Ledger and DCAS data

- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/gossip/state/state.go
- mod/peer/gossip/state/state_test.go
- scripts/pull_fabric.sh
provided default implementation for #141 for stabilizing the build
subsequent commits will have actual implementation
> feat: default implementation for role based gossip state provider

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/gossip/state/state.go
- mod/peer/gossip/state/state_test.go
- scripts/pull_fabric.sh
- updating with respect to latest fabric-mod changes
- addressed #141
> feat: gossip state provider extension updates

- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore_provider.go
Implements #145
Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>
> refactor: OffLedger Data provider - CouchDB config fetch

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/gossip/api/gossipapi.go
- mod/peer/gossip/state/state.go
- mod/peer/gossip/state/state_test.go
- mod/peer/roles/ledger_roles_config.go
- mod/peer/roles/ledger_roles_config_test.go
- pkg/gossip/blockpublisher/blockpublisher.go
- pkg/mocks/mockblockhandler.go
- pkg/roles/roles.go
- scripts/pull_fabric.sh
- provided implementation for gossip state provider extensions.
- addresses #141 
> feat: role based features in gossip state provider extension

- mod/peer/gossip/dispatcher/dispatcher_test.go
- pkg/collections/client/client.go
- pkg/collections/client/client_test.go
- pkg/collections/offledger/dcas/client/dcasclient_test.go
- pkg/common/support/collconfigretriever_test.go
- pkg/common/support/support_test.go
- pkg/endorser/endorser_test.go
- pkg/gossip/dispatcher/dispatcher_test.go
- pkg/mocks/mockqueryexecutor.go
- pkg/mocks/mockresultsiterator.go
Added Query function in the off-ledger/DCAS client.
closes #162
> feat: Support rich queries in off-ledger and DCAS client

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/gossip/api/gossipapi.go
- mod/peer/gossip/state/state.go
- pkg/collections/offledger/retriever/olretriever.go
- pkg/collections/offledger/retriever/olretriever_test.go
- pkg/collections/transientdata/retriever/transientdataretriever.go
- pkg/collections/transientdata/retriever/transientdataretriever_test.go
- pkg/common/support/collconfigretriever.go
- pkg/common/support/collconfigretriever_test.go
- pkg/gossip/blockpublisher/blockpublisher.go
- pkg/mocks/mockblockhandler.go
- scripts/pull_fabric.sh
> feat: Add txIndex for BlockPublisher handlers

- .codecov.yaml
- .gitignore
- .travis.yml
- Makefile
- mod/peer/storage/idstore/store.go
- pkg/idstore/couchdoc_conv.go
- pkg/idstore/store_impl.go
- pkg/idstore/store_impl_test.go
- pkg/idstore/test_exports.go
- pkg/roles/roles_test.go
- scripts/unit.sh
> ci: Add codecov

- .codecov.yaml
- Makefile
- pkg/pvtdatastorage/cachedpvtdatastore/store_impl.go
- pkg/pvtdatastorage/cachedpvtdatastore/store_impl_test.go
- pkg/pvtdatastorage/cdbpvtdatastore/couchdb_conv.go
- pkg/pvtdatastorage/cdbpvtdatastore/store_impl.go
- pkg/pvtdatastorage/cdbpvtdatastore/store_impl_test.go
- pkg/pvtdatastorage/common/store.go
- pkg/pvtdatastorage/common/v11.go
- pkg/pvtdatastorage/store_impl.go
- pkg/pvtdatastorage/store_impl_test.go
> test: Improve pvtdatastorage codecov

- mod/peer/roles/ledger_roles_config_test.go
- pkg/roles/roles.go
- pkg/roles/roles_test.go
> feat: Add default value for fabric roles if not defined

- go.mod
- go.sum
- mod/peer/channel/channel.go
- mod/peer/channel/channel_test.go
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/gossip/api/gossipapi.go
- mod/peer/gossip/mocks/blockpublisher.go
- mod/peer/gossip/service/service.go
- mod/peer/gossip/service/service_test.go
- mod/peer/gossip/state/state.go
- mod/peer/gossip/state/state_test.go
- pkg/gossip/blockpublisher/blockpublisher.go
- pkg/gossip/blockpublisher/blockpublisher_test.go
- pkg/mocks/mockblockpublisher.go
- scripts/pull_fabric.sh
- role based extension in anti entropy while request new blocks
- role based extension for ledger height calculations
- ChannelInitializer extension to use current config block
- role based extension for gossip in deliveryservice  blocks provider
- block publisher to provide ledger height info
related to #141
> feat: role based features

- pkg/transientstore/store_test.go
Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>
> chore: increase transientstore test coverage

- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore.go
- test/bddtests/features/off_ledger.feature
- test/bddtests/features/step_definitions/offledger_steps.ts
- test/bddtests/fixtures/testdata/src/github.com/trustbloc/e2e_cc/e2e_cc.go
- test/bddtests/go.mod
- test/bddtests/go.sum
- test/bddtests/offledger_steps.go
Added BDD steps that ensure the query results have proper keys and values for off-ledger/DCAS collection types.
closes #191
> test: Enhancements to off-ledger/DCAS query integration tests

- .golangci.yml
- pkg/collections/offledger/retriever/olretriever.go
- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore.go
- pkg/collections/transientdata/retriever/transientdataretriever.go
- pkg/idstore/store_impl.go
- scripts/check_lint.sh
Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>
> ci: GolangCI Lint - Update docker image source, fix lint errors and and remove webhook config

- test/bddtests/features/transient_data.feature
Modified the transient data BDD test to start with a chaincode that has no transient data collections and then add the transient data collections in an upgrade.
closes #214
> test: Added BDD test for new transient data collection in upgrade

- mod/peer/roles/ledger_roles_config_test.go
- pkg/roles/roles.go
- pkg/roles/roles_test.go
- pkg/roles/test_exports.go
Fix for concurrent map modifications in roles.
closes #218
> fix: Concurrent write to map

- pkg/collections/transientdata/dissemination/disseminator.go
- pkg/collections/transientdata/dissemination/disseminator_test.go
- Return error if cannot resolve to any orgs
- Return error if cannot resolve to any endorsers
- Stop looping if all endorsers have already been added even though MaxPeerCount has not been met
closes #221
> refactor: Handle edge cases in transient data dissemination

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- scripts/pull_fabric.sh
Point to the latest fabric-peer-mod which includes a performance improvement for pulling private data from remote peers.
closes #223
> chore: Point to latest fabric-peer-mod

- pkg/common/compositekey/compositekey.go
- pkg/common/compositekey/compositkey_test.go
- pkg/config/ledgerconfig/mgr/querymgr.go
- pkg/config/ledgerconfig/mgr/querymgr_test.go
- pkg/config/ledgerconfig/mgr/updatemgr.go
- pkg/config/ledgerconfig/mocks/mockkvresultsiter.go
- pkg/config/ledgerconfig/mocks/mockretrieverprovider.go
- pkg/config/ledgerconfig/mocks/mockstateretriever.go
- pkg/config/ledgerconfig/mocks/mockstoreprovider.go
- pkg/config/ledgerconfig/state/api/api.go
- pkg/mocks/mockqueryexecutor.go
Implemented QueryManager which allows clients to query for one or more config items using search criteria.
closes #227
> feat: Query ledger configuration

- pkg/config/ledgerconfig/mgr/keyvaluemap.go
- pkg/config/ledgerconfig/mgr/updatemgr.go
- pkg/config/ledgerconfig/mgr/updatemgr_test.go
- pkg/config/ledgerconfig/mocks/mockstoreprovider.go
- pkg/config/ledgerconfig/state/api/api.go
- pkg/mocks/mockqueryexecutor.go
Added function to UpdateManager that allows clients to delete one or more config items using criteria.
closes #228
> feat: Delete ledger configuration

- cmd/chaincode/configscc/configscc.go
- cmd/chaincode/configscc/configscc_test.go
- pkg/config/ledgerconfig/mocks/mockconfigmgr.go
Added a system chaincode that can write/read/delete ledger configuration data.
closes #167
> feat: Configuration system chaincode

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/ledgerconfig/service/service.go
- pkg/config/ledgerconfig/service/service_test.go
Added function, AddUpdateHandler, to allow a client to subscribe for notifications about updated configuration.
closes #239
> feat: Notification on configuration update

- .golangci.yml
- scripts/check_lint.sh
> chore: Use golangci-lint v1.20

- README.md
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
> ci: update build badge to azp

- .ci-properties
> chore: Change BASE_VERSION to 0.1.1

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/gossip/blockpublisher/blockpublisher.go
- mod/peer/gossip/blockpublisher/blockpublisher_test.go
- mod/peer/gossip/state/state.go
- mod/peer/storage/statedb/statedb.go
- mod/peer/storage/statedb/statedb_test.go
- pkg/collections/client/client.go
- scripts/pull_fabric.sh
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
> feat: Update to latest fabric-mod with new block publisher provider

- pkg/config/ledgerconfig/config/keyvalue.go
- pkg/config/ledgerconfig/config/keyvalue_test.go
- pkg/config/ledgerconfig/mgr/querymgr_test.go
- pkg/config/ledgerconfig/mocks/mockkvresultsiter.go
- pkg/config/ledgerconfig/state/kvresultsiter.go
- pkg/config/ledgerconfig/state/qestateretriever_test.go
- pkg/mocks/mockqueryexecutor.go
- test/bddtests/features/ledger_config.feature
Changed the query results type from statedb.VersionedKV to queryresult.KV.
Also, fixed a typo in the Key.String() func.
closes #332
> fix: Fix type assertion in ledger config query

- pkg/config/ledgerconfig/config/service.go
- pkg/config/ledgerconfig/service/service.go
- pkg/config/ledgerconfig/service/service_test.go
- pkg/txn/mocks/configservice.gen.go
- test/bddtests/config_steps.go
- test/bddtests/features/ledger_config.feature
- test/cc/testcc/testcc.go
Implemented a Query function on the configuration service that accepts criteris and returns 0 or more results.
closes #342
> feat: Added Query function to config service

- .ci-properties
> chore: Change release version to 0.1.2

- scripts/pull_fabric.sh
> fix: Ensure build works on Mac as well as Linux

- pkg/collections/offledger/dissemination/disseminationplan.go
- pkg/collections/offledger/dissemination/disseminator.go
- pkg/collections/offledger/dissemination/disseminator_test.go
> fix: Don't include local peer in dissemination plan

- pkg/common/blockvisitor/blockvisitor.go
- pkg/common/blockvisitor/blockvisitor_test.go
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
> fix: Set TxNum on block visitor events

- scripts/integration.sh
- test/bddtests/bddtests_test.go
- test/bddtests/features/gossip_appdata.feature
- test/bddtests/fixtures/docker-compose-base.yml
- test/bddtests/fixtures/fabric/peer/cmd/main.go
- test/cc/hellocc/hellocc.go
> test: Added BDD test for app-specific Gossip message

- mod/peer/go.mod
- pkg/txn/api/api.go
- pkg/txn/api/service.go
- pkg/txn/client/client.go
- pkg/txn/client/client_test.go
- pkg/txn/handler/commit.go
- pkg/txn/mocks/txnclient.gen.go
- pkg/txn/service.go
- pkg/txn/service_test.go
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
> feat: Added Txn service function to get peer by endpoint

- test/bddtests/features/step_definitions/txn_steps.js
- test/bddtests/features/txn.feature
- test/bddtests/go.mod
- test/bddtests/txn_steps.go
- test/handler/exampleauthfilter/exampleauthfilter.go
> test: Added BDD tests for ValidateProposalResponses and VerifyProposalSignature

- pkg/txn/proprespvalidator/validator.go
> fix: Check for nil chaincode spec in proposal response

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- scripts/pull_fabric.sh
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
> chore: Update to Fabric 2.2.0

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/storage/api/api.go
- mod/peer/testutil/ext_test_env.go
- pkg/idstore/couchdoc_conv.go
- pkg/idstore/store_impl.go
- pkg/idstore/store_impl_test.go
- scripts/pull_fabric.sh
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
Implemented:
- UpdateLedgerStatus
- GetFormat
- UpgradeFormat
Fixed:
- GetActiveLedgerIDs
- LedgerIDActive
closes #318
> fix: Implemented missing ID store functions

- pkg/pvtdatastorage/cdbpvtdatastore/store_impl.go
- pkg/pvtdatastorage/cdbpvtdatastore/store_impl_test.go
- pkg/pvtdatastorage/common/collelgproc.go
- pkg/pvtdatastorage/common/store.go
> fix: Update implementation of pvtdatastorage processCollElgEvents

- go.sum
- mod/peer/storage/idstore/mocks/idstore.gen.go
> fix: Fix import path

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- scripts/pull_fabric.sh
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
- Enable TestRollbackCmd
part #449
> chore: update fabric-mod revision

- mod/peer/ledger/kvledger/drop_dbs.go
- mod/peer/ledger/kvledger/ledger_filepath.go
- mod/peer/ledger/kvledger/rollback.go
> feat: Drop stateCouchDB in drop_db.go

- mod/peer/ledger/kvledger/rebuild_dbs.go
- mod/peer/ledger/kvledger/rebuild_dbs_test.go
- pkg/blkstorage/cdbblkstorage/reset.go
> feat: Implement RebuildDBs

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/ledger/kvledger/upgrade_dbs.go
- mod/peer/ledger/kvledger/upgrade_dbs_test.go
- pkg/idstore/test_exports.go
- scripts/pull_fabric.sh
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
> feat: Implement UpgradeDBs

- mod/peer/ledger/kvledger/kv_ledger_provider_test.go
- pkg/idstore/test_exports.go
- Add TestLedgerMetataDataUnmarshalError
part #447
> fix: Add unit tests for CouchDB ID store

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/ledger/kvledger/pause_resume.go
- mod/peer/ledger/kvledger/pause_resume_test.go
- pkg/idstore/store_impl.go
- pkg/idstore/store_impl_test.go
- pkg/idstore/test_exports.go
- scripts/pull_fabric.sh
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
> fix: Add PauseAndResume logic

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/ledger/kvledger/reset.go
- pkg/blkstorage/cdbblkstorage/cdb_blkstorage_provider.go
- pkg/blkstorage/cdbblkstorage/cdb_blkstorage_provider_test.go
- pkg/blkstorage/cdbblkstorage/reset.go
- scripts/pull_fabric.sh
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
> fix: Implement Reset KV Ledger

- mod/peer/ledger/kvledger/rollback.go
- pkg/blkstorage/cdbblkstorage/couchdoc_conv.go
- pkg/blkstorage/cdbblkstorage/rollback.go
> fix: Handle couchDB docRange limit in rollback.go

- mod/peer/ledger/kvledger/drop_dbs.go
- mod/peer/ledger/kvledger/rebuild_dbs.go
- mod/peer/ledger/kvledger/rebuild_dbs_test.go
- mod/peer/ledger/kvledger/upgrade_dbs.go
- pkg/blkstorage/cdbblkstorage/reset.go
> fix: Remove drop block store

- pkg/chaincode/notifier/notifier.go
- pkg/txn/handler/commit.go
> fix: Changed Info logs to Debug

- pkg/blkstorage/cdbblkstorage/cdb_blkstorage.go
Blockchain info is now cached so that it doesn't need to be retrieved from the database.
closes #439
> feat: Cache blockchain info

- go.mod
- go.sum
- mod/peer/go.sum
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
- test/bddtests/go.mod
- test/bddtests/go.sum
> chore: Bump fabric-sdk-go to v1.0.0-beta3

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- pkg/pvtdatastorage/cdbpvtdatastore/couchdb_conv.go
- pkg/pvtdatastorage/cdbpvtdatastore/reconcile_missing_pvtdata.go
- pkg/pvtdatastorage/cdbpvtdatastore/reconcile_missing_pvtdata_test.go
- pkg/pvtdatastorage/cdbpvtdatastore/store_impl.go
- pkg/pvtdatastorage/cdbpvtdatastore/store_impl_test.go
- pkg/pvtdatastorage/cdbpvtdatastore/test_exports.go
- pkg/pvtdatastorage/common/collelgproc.go
- pkg/pvtdatastorage/common/helper.go
- pkg/pvtdatastorage/common/kv_encoding.go
- pkg/pvtdatastorage/common/store.go
- pkg/testutil/ext_test_env.go
- scripts/pull_fabric.sh
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
> fix: Implement 'Deprioritize fetching of missing pvt data after multiple retries'

- pkg/collections/offledger/dcas/client/dcasclient.go
- pkg/collections/offledger/dcas/client/dcasclient_test.go
- pkg/collections/offledger/dcas/client/provider.go
- pkg/collections/offledger/dcas/client/provider_test.go
- test/bddtests/features/lc_off_ledger.feature
Refactored the DCAS client API in preparation for #526 - Support IPFS CIDs in DCAS.
closes #529
> refactor: Refactor the DCAS client API

- go.mod
- go.sum
- mod/peer/config/config.go
- mod/peer/config/config_test.go
- mod/peer/go.mod
- mod/peer/go.sum
- pkg/config/config.go
- pkg/config/config_test.go
- scripts/pull_fabric.sh
- test/bddtests/fixtures/docker-compose-base.yml
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
> feat: Added config to skip checks for duplicate transactions on endorser

- pkg/validation/validationhandler/validationhandler.go
- pkg/validation/validationhandler/validationhandler_test.go
- pkg/validation/validator/validator.go
- pkg/validation/validator/validator_test.go
- test/bddtests/bddtests_test.go
- test/bddtests/features/gossip_appdata.feature
- test/bddtests/features/lc_gossip_appdata.feature
- test/bddtests/fixtures/config/fabric/core.yaml
- test/bddtests/fixtures/config/sdk-client/config.yaml
- test/bddtests/fixtures/docker-compose-base.yml
- test/bddtests/fixtures/docker-compose-nocluster.yml
- test/bddtests/fixtures/docker-compose.yml
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
- test/bddtests/fixtures/fabric/v1.4/config/cryptogen.yaml
- test/bddtests/fixtures/fabric/v2.2/config/configtx.yaml
- test/bddtests/fixtures/fabric/v2.2/config/cryptogen.yaml
Added a third peer to each org and added the 'validator' role to the non-committing peers.
Also added missing unit tests for the validator.
closes #562
> test: Enable distributed validation in BDD tests
