trustbloc/fabric-peer-ext

- go.mod
- go.sum
- mod/peer/collections/dissemination/disseminationplan.go
- mod/peer/collections/dissemination/disseminationplan_test.go
- mod/peer/go.mod
- pkg/collections/transientdata/dissemination/disseminationplan.go
- pkg/collections/transientdata/dissemination/disseminator.go
- pkg/collections/transientdata/dissemination/disseminator_test.go
- pkg/common/discovery/discovery.go
- pkg/common/discovery/discovery_test.go
- pkg/common/discovery/member.go
- pkg/common/discovery/member_test.go
- pkg/common/discovery/peergroup.go
- pkg/common/discovery/peergroup_test.go
- pkg/mocks/mockaccesspolicy.go
- pkg/mocks/mockgossipadapter.go
Implemented a dissemination plan for transient data that is based on a deterministic algorithm.
The hash of the key is used first to determine the org to which to disseminate and then the
same hash is used to select the peer within the org. The number of peers to which to disseminate
is specific in the collection policy by 'maxPeers'.
closes #54
> feat: Transient Data Dissemination

- pkg/collections/transientdata/storeprovider/store/cache/cache.go
- pkg/collections/transientdata/storeprovider/store/cache/cache_test.go
- pkg/config/config.go
- pkg/config/config_test.go
Implemented an LRU cache for transient data. Transient data
is cached in memory and expired according to the provided
expiration time. If the cache reaches capacity, evicted items
are transferred to persistent store. If the evicted item is
later requested, it is loaded from persistent store.
closes #51
> feat: Transient Data Cache

- mod/peer/collections/retriever/retriever.go
- mod/peer/gossip/blockpublisher/blockpublisher.go
- mod/peer/gossip/blockpublisher/blockpublisher_test.go
- mod/peer/gossip/dispatcher/dispatcher.go
- mod/peer/gossip/dispatcher/dispatcher_test.go
- pkg/collections/pvtdatastore/pvtdatastore.go
- pkg/collections/retriever/retriever.go
- pkg/collections/retriever/retriever_test.go
- pkg/collections/transientdata/retriever/transientdataretriever.go
- pkg/collections/transientdata/retriever/transientdataretriever_test.go
- pkg/common/multirequest/multirequest.go
- pkg/common/requestmgr/requestmgr.go
- pkg/common/support/collconfigretriever.go
- pkg/common/support/collconfigretriever_test.go
- pkg/common/support/support.go
- pkg/common/support/support_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/gossip/blockpublisher/blockpublisher.go
- pkg/gossip/blockpublisher/blockpublisher_test.go
- pkg/gossip/dispatcher/dispatcher.go
- pkg/gossip/dispatcher/dispatcher_test.go
- pkg/mocks/mockblockbuilder.go
- pkg/mocks/mockblockhandler.go
- pkg/mocks/mockblockpublisher.go
- pkg/mocks/mocksupport.go
When a chaincode is upgraded then all collection policy caches
for that chaincode are cleared.
closes #61
> feat: Clear Caches on Chaincode Upgrade

- mod/peer/endorser/endorser.go
- pkg/endorser/endorser.go
- pkg/endorser/endorser_test.go
- pkg/mocks/mockrwsetbuilder.go
Transient data read-write sets are filtered out from the simulation
resuls before endorsement so as not to show up on the ledger.
closes #88
> feat: Remove transient data read-write sets from simulation results

- mod/peer/collections/pvtdatahandler/pvtdatahandler.go
- mod/peer/collections/pvtdatahandler/pvtdatahandler_test.go
- pkg/collections/pvtdatahandler/pvtdatahandler.go
- pkg/collections/pvtdatahandler/pvtdatahandler_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/mocks/mockdataprovider.go
Implement a handler for GetPrivateData that returns transient
data if the collection type is transient.
closes #108
> fix: Fix bug in transient data retrieval

- pkg/collections/client/client.go
- pkg/collections/client/client_test.go
Added an client API that allows you to persist and retrieve off-ledger
collection data (including transient data) from outside of a chaincode.
closes #56
> feat: Collection Client

- go.sum
- pkg/collections/offledger/storeprovider/store/cache/cache.go
- pkg/collections/offledger/storeprovider/store/cache/cache_test.go
- pkg/collections/offledger/storeprovider/store/mocks/mockdbprovider.go
Implement a cache in front of Off-Ledger collections. The item is stored
in the cache and in the DB but retrieved from the cache. On cache-miss,
the item is loaded from the DB.
closes #59
> feat: LRU for Off-Ledger Collections

- mod/peer/collections/api/store/provider.go
- mod/peer/gossip/coordinator/coordinator_test.go
- mod/peer/mocks/mockdatastore.go
- pkg/collections/offledger/api/offledger.go
- pkg/collections/offledger/storeprovider/olstore.go
- pkg/collections/offledger/storeprovider/olstore_test.go
- pkg/collections/offledger/storeprovider/olstoreprovider.go
- pkg/collections/offledger/storeprovider/olstoreprovider_test.go
- pkg/collections/pvtdatastore/pvtdatastore_test.go
- pkg/collections/storeprovider/mocks/mockolstore.go
- pkg/collections/storeprovider/store.go
- pkg/collections/storeprovider/storeprovider.go
- pkg/collections/storeprovider/storeprovider_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/endorser/endorser.go
- pkg/endorser/endorser_test.go
- pkg/mocks/mockdatastore.go
- pkg/mocks/mockrwsetbuilder.go
During endorsement, traverse the read-write sets and store off-ledger data
to the database and cache.
closes #60
> feat: Extract Off-Ledger data from read/write sets and persist

- mod/peer/collections/api/store/provider.go
- mod/peer/collections/retriever/retriever_test.go
- mod/peer/mocks/mockprovider.go
- pkg/collections/offledger/api/offledger.go
- pkg/collections/offledger/dissemination/disseminator.go
- pkg/collections/offledger/mocks/mockprovider.go
- pkg/collections/offledger/retriever/olprovider.go
- pkg/collections/offledger/retriever/olprovider_test.go
- pkg/collections/offledger/storeprovider/olstore.go
- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore.go
- pkg/collections/offledger/storeprovider/store/leveldbstore/dbstore.go
- pkg/collections/pvtdatahandler/pvtdatahandler.go
- pkg/collections/pvtdatahandler/pvtdatahandler_test.go
- pkg/collections/retriever/retriever.go
- pkg/collections/retriever/retriever_test.go
- pkg/collections/retriever/test_exports.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/mocks/mockdataprovider.go
Retrieve Off-Ledger data from the current peer. If the data does not exist
then a Gossip message is sent to other peers requesting the data. Once the
data is successfully retrieved, it is stored on the current peer.
Note that before retrieving the data, a check is made to see if the current
peer has access to the data (according to collection policy). If the peer
does not have access, then nil is returned.
closes #63
> feat: Retrieve Off-Ledger data

- scripts/generate_channeltx.sh
- test/bddtests/features/transient_data.feature
- test/bddtests/fixtures/config/sdk-client/config.yaml
- test/bddtests/fixtures/testdata/src/github.com/trustbloc/e2e_cc/e2e_cc.go
Added a BDD test to ensure that a chaincode is able to read and write transient data
from another chaincode using the stub function, InvokeChaincode. Both reads and writes
should work if invoking chaincode on the same channel as the source chaincode. Reads
should work if invoking chaincode on a different channel.
closes #119
> test: Added test for Chaincode-to-Chaincode Transient Data

- go.mod
- go.sum
- mod/peer/collections/dissemination/disseminationplan.go
- mod/peer/collections/dissemination/disseminationplan_test.go
- mod/peer/collections/policy/validator.go
- mod/peer/collections/policy/validator_test.go
- mod/peer/go.sum
- pkg/collections/offledger/dcas/cas.go
- pkg/collections/offledger/dcas/cas_test.go
- pkg/collections/offledger/dcas/dcas.go
- pkg/collections/offledger/dcas/dcas_test.go
- pkg/collections/offledger/dissemination/disseminationplan.go
- pkg/collections/offledger/dissemination/disseminator_test.go
- pkg/collections/offledger/policy/validator.go
- pkg/collections/offledger/policy/validator_test.go
- pkg/collections/offledger/retriever/olretriever.go
- pkg/collections/offledger/retriever/olretriever_test.go
- pkg/collections/offledger/storeprovider/olstore_test.go
- pkg/collections/offledger/storeprovider/olstoreprovider_test.go
- pkg/collections/pvtdatahandler/pvtdatahandler.go
- pkg/collections/pvtdatahandler/pvtdatahandler_test.go
- pkg/collections/retriever/retriever.go
- pkg/collections/storeprovider/storeprovider.go
- pkg/endorser/endorser.go
- pkg/endorser/endorser_test.go
- pkg/mocks/mocksupport.go
Added a Distributed Content Addressable Store (DCAS) collection which uses the existing,
off-ledger implementation with additional validation. The DCAS collection behaves exactly
the same as Off-Ledger except that when a DCAS key/value is stored then:
- If the key is specified then the key should be validated to be the hash of the value
- If the key is empty ("") then the key should be generated to be the hash of the value
closes #66 
> feat: DCAS Collection Type

- pkg/gossip/dispatcher/dispatcher.go
- pkg/gossip/dispatcher/dispatcher_test.go
DCAS and Off-Ledger collections were not being handled by the Gossip dispatcher.
This fix adds handling for those collection types.
closes #125
> fix: Dispatch Off-Ledger and DCAS collections

- pkg/collections/client/test_exports.go
- pkg/collections/offledger/dcas/client/dcasclient.go
- pkg/collections/offledger/dcas/client/dcasclient_test.go
Added a client to store/retrieve DCAS data from outside of a chaincode. The put function
accepts the collection name and value as arguments and returns the key, which is the hash
of the value.
closes #67
> feat: DCAS Client

- pkg/collections/offledger/dcas/cas.go
- pkg/collections/offledger/dcas/cas_test.go
- pkg/collections/offledger/dcas/dcas.go
- pkg/collections/offledger/dcas/dcas_test.go
- pkg/collections/offledger/retriever/olretriever.go
- pkg/collections/offledger/retriever/olretriever_test.go
- pkg/collections/offledger/storeprovider/olstore_test.go
- pkg/collections/retriever/retriever.go
This change hides the fact that the CAS key is encoded in base58 when storing
to the DB. Clients can now use base64 encoded keys when storing/retrieving DCAS
data and the base58 encoding is performed internally.
closes #130
> fix: CAS keys should be base64 encoded

- README.md
The Go version was updated as part of PR #124 to 1.12.x. Updated ReadMe file with new Go version.
Closes #138
Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>
> docs: Update Go dependency Version in README

- go.mod
- go.sum
- mod/peer/endorser/api/endorser.go
- mod/peer/endorser/endorser.go
- mod/peer/endorser/endorser_test.go
- mod/peer/go.mod
- mod/peer/go.sum
- pkg/endorser/endorser.go
- pkg/endorser/endorser_test.go
- scripts/pull_fabric.sh
- test/bddtests/features/transient_data.feature
- test/bddtests/fixtures/testdata/src/github.com/trustbloc/e2e_cc/e2e_cc.go
The collection config package that is assembled by the endorser removes
configs for collections in which there was no write set and therefore
the error 'config for collection [xxx] not found' results. Thes commit
removes the dependency on the collection config package and uses the
collection config retriever to manage collection configs.
closes #158
> fix: Fix for collection config not found

- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore_provider.go
- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore_test.go
- pkg/config/config.go
- pkg/config/config_test.go
Defer the creation of the CouchDB instance until first use. Also, don't start the purge Go routine until the first DB has been created.
closes #160
> refactor: Defer the creation of the CouchDB instance

- go.sum
- pkg/collections/offledger/storeprovider/olstore.go
- pkg/collections/offledger/storeprovider/store/api/api.go
- pkg/collections/offledger/storeprovider/store/cache/cache.go
- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore.go
- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore_provider.go
- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore_test.go
- pkg/collections/offledger/storeprovider/store/leveldbstore/dbstore_provider.go
- pkg/collections/offledger/storeprovider/store/leveldbstore/dbstore_test.go
- pkg/collections/offledger/storeprovider/store/mocks/mockdbprovider.go
- test/bddtests/features/off_ledger.feature
- test/bddtests/features/step_definitions/offledger_steps.ts
- test/bddtests/fixtures/testdata/src/github.com/trustbloc/e2e_cc/META-INF/statedb/couchdb/collections/accounts/indexes/indexID.json
- test/bddtests/fixtures/testdata/src/github.com/trustbloc/e2e_cc/e2e_cc.go
- test/bddtests/go.sum
- test/bddtests/offledger_steps.go
Refactored the CouchDB store so that JSON documents are stored as first-class
fields in the Couch document. This way, the standard rich-query API,
GetPrivateDataQueryResult, may be used to retrieved data from DCAS and off-ledger
stores.
closes #155
> feat: Add support for rich queries in off-ledger and DCAS

- go.mod
- go.sum
- mod/peer/chaincode/scc.go
- mod/peer/chaincode/scc_test.go
- mod/peer/go.mod
- mod/peer/go.sum
- pkg/chaincode/scc/builder/sccbuilder.go
- pkg/chaincode/scc/builder/sccbuilder_test.go
- pkg/chaincode/scc/scc.go
- pkg/chaincode/scc/scc_test.go
- pkg/common/injectinvoker/injectinvoker.go
- pkg/common/injectinvoker/injectinvoker_test.go
- pkg/mocks/mockqueryexecutor.go
- scripts/pull_fabric.sh
Allow extensions to register custom system chaincodes. The system chaincode should be provided with all required dependencies, e.g. ledger, gossip, etc.
closes #171
> feat: Extended System Chaincodes

- pkg/collections/client/client.go
Move the call to GetBlockchainInfo before acquiring the Tx Simulator, since the Tx Simulator acquires a Write lock and the call to GetBlockchainInfo attempts to acquire a read lock.
closes #178
> fix: Deadlock in off-ledger client

- test/bddtests/fixtures/config/sdk-client/config.yaml
- test/bddtests/fixtures/docker-compose.yml
- each org will use same couchdb for block, private data, config history
and transient storage
- each peers will have specific roles - ENDORSER or COMMITTER
- in bdd tests client config, event source for endorserer peers are
disabled since endorser are still having issues with event delivery
-related #141 
> feat: bddtests to use couchdb cluster

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/gossip/service/service.go
- mod/peer/gossip/service/service_test.go
- mod/peer/gossip/state/state.go
- mod/peer/gossip/state/state_test.go
- mod/peer/ledger/api/ledgerapi.go
- mod/peer/ledger/kvledger.go
- mod/peer/ledger/kvledger_test.go
- mod/peer/storage/blkstorage/api/blkstorageapi.go
- pkg/blkstorage/cdbblkstorage/cdb_blkstorage.go
- pkg/blkstorage/cdbblkstorage/cdb_blockstorage_test.go
- pkg/mocks/mockledger.go
- scripts/pull_fabric.sh
- test/bddtests/fixtures/config/sdk-client/config.yaml
- test/bddtests/fixtures/docker-compose.yml
- added new extension function which can be used to extend private data
reconciler flag
- using blocking mode from gossip state in gossip state extensions
- added Checkpoint block feature in couchdb blockstore
related to #141
> feat: pvtdata reconciller for committer and checkpoint block in blockstore

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/gossip/blockpublisher/blockpublisher.go
- mod/peer/gossip/blockpublisher/blockpublisher_test.go
- mod/peer/storage/statedb/statedb.go
- mod/peer/storage/statedb/statedb_test.go
- pkg/collections/client/client.go
- pkg/collections/client/client_test.go
- pkg/collections/offledger/storeprovider/olstore.go
- pkg/collections/offledger/storeprovider/olstore_test.go
- pkg/collections/offledger/storeprovider/olstoreprovider_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- scripts/pull_fabric.sh
- test/bddtests/features/off_ledger.feature
- test/bddtests/fixtures/config/sdk-client/config.yaml
- test/bddtests/fixtures/docker-compose.yml
- added CC upgrade hanlder in statedb which will be used to update lscc
state cache whenever CC upgrade takes place in case of endorsers
- re -enabled roles in bddtests docker
- related to #141
> feat: CC upgrade Handler in statedb

- pkg/collections/offledger/dcas/cas.go
- pkg/collections/offledger/dcas/cas_test.go
- pkg/collections/offledger/dcas/client/dcasclient.go
- pkg/collections/offledger/dcas/client/dcasclient_test.go
- pkg/collections/offledger/dcas/dcas.go
- pkg/collections/offledger/dcas/dcas_test.go
- pkg/collections/offledger/dissemination/disseminationplan.go
- pkg/collections/offledger/dissemination/disseminator_test.go
- pkg/collections/offledger/retriever/olretriever_test.go
- pkg/collections/offledger/storeprovider/olstore_test.go
- pkg/mocks/mockqueryexecutor.go
Update the DCAS client to use only base64-encoded keys. The DCAS client encodes the key in base58 before storing it and decodes the key from base58 before returning the key to the caller.
closes #200
> fix: Use base64-encoded keys in DCAS client API

- go.mod
- go.sum
- mod/peer/endorser/endorser.go
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/gossip/dispatcher/dispatcher.go
- mod/peer/gossip/state/state.go
- pkg/collections/client/client.go
- pkg/collections/retriever/retriever.go
- pkg/collections/transientdata/storeprovider/tdstore.go
- pkg/common/support/collconfigretriever.go
- pkg/common/support/collconfigretriever_test.go
- pkg/common/support/support.go
- pkg/common/support/support_test.go
- pkg/endorser/endorser.go
- pkg/endorser/endorser_test.go
- pkg/gossip/dispatcher/dispatcher.go
- pkg/gossip/dispatcher/dispatcher_test.go
- scripts/pull_fabric.sh
Intermittent deadlocks occur attempting to retrieve transient data. When a block is being committed, the committer attempts to acquire a write lock while the chaincode already has a read-lock. Then GetPrivateData attempts to acquire a read-lock to retrieve collection config data from the ledger. This commit adds an LSCC handler to the collection config retriever so that the collection config cache is populated directly from the data provided by the handler which eliminates the need to pull the config from the ledger.
closes #202
> fix: Deadlock retrieving transient data

- pkg/collections/transientdata/dissemination/disseminationplan.go
- pkg/collections/transientdata/dissemination/disseminator.go
- pkg/collections/transientdata/dissemination/disseminator_test.go
- test/bddtests/features/transient_data.feature
The dissemination logic was changed in order to ensure that each endorser is disseminated all applicable keys. Initially only one dissemination plan was created for all peers and this was causing some peers to miss data since the MaxPeerCount was reached. This patch creates multiple dissemination plans - one per peer - which includes all keys applicable to the endorser.
closes #210
> fix: Dissemination of multiple transient data keys

- pkg/collections/transientdata/storeprovider/store/cache/cache.go
- pkg/collections/transientdata/storeprovider/store/cache/cache_test.go
- pkg/collections/transientdata/storeprovider/store/dbstore/dbstore.go
- pkg/collections/transientdata/storeprovider/store/dbstore/dbstore_test.go
- pkg/collections/transientdata/storeprovider/tdstore.go
- pkg/collections/transientdata/storeprovider/tdstore_test.go
This patch adds a check during persistence of transient data to make sure that the key is assigned to the peer. If not then it is not stored locally (but still disseminated to other peers).
Also, changed the name of the loggers for all sub-packages of transientdata to be consistent in order to help in debugging.
closes #211
> fix: Don't store transient data on endorser if not assigned

- test/bddtests/features/off_ledger.feature
- test/bddtests/features/step_definitions/common_steps.js
- test/bddtests/features/transient_data.feature
- test/bddtests/go.mod
- test/bddtests/go.sum
Added a BDD test to ensure a collection's type cannot be changed during a chaincode upgrade.
closes #216
> test: Add test for collection type modification in upgrade

- pkg/config/ledgerconfig/state/shimstatestore.go
- pkg/config/ledgerconfig/state/shimstatestore_test.go
Implemented a state store provider that uses the chaincode stub to store and retrieve data.
closes #233
> feat: Shim state store provider

- pkg/config/ledgerconfig/state/kvresultsiter.go
- pkg/config/ledgerconfig/state/qestateretriever.go
- pkg/config/ledgerconfig/state/qestateretriever_test.go
- pkg/mocks/mockqueryexecutor.go
Implemented a ledger configuration state retriever based on the ledger's QueryExecutor.
closes #235
> feat: Query executor state retriever

- pkg/config/ledgerconfig/config/criteria.go
- pkg/config/ledgerconfig/config/criteria_test.go
- pkg/config/ledgerconfig/config/keyvalue.go
- pkg/config/ledgerconfig/config/keyvalue_test.go
- pkg/config/ledgerconfig/service/service.go
- pkg/config/ledgerconfig/service/service_test.go
- pkg/config/ledgerconfig/service/servicemgr.go
Implement a configuration service that allows a peer's local resources (such as system chaincode) to read configuration data from the ledger.
closes #237
> feat: Configuration service

- cmd/chaincode/configscc/configscc.go
- cmd/chaincode/configscc/configscc_test.go
- pkg/config/ledgerconfig/service/service.go
- pkg/config/ledgerconfig/service/service_test.go
- pkg/config/ledgerconfig/service/servicemgr.go
- pkg/mocks/mockblockpublisher.go
Added a cache to the config service. The cache is populated on demand, i.e. if the config key does not exist then it is loaded using the Retriever.
The service registers with a block publisher to receive notifications of writes to the ledger. An update handler adds/updates/removes keys as it receives notifications from the block publisher.
closes #169
> feat: Configuration cache

- test/bddtests/features/ledger_config.feature
- test/bddtests/fixtures/config/fabric/core.yaml
- test/bddtests/fixtures/fabric/peer/cmd/main.go
- test/scc/testscc/testscc.go
Added a BDD test for the local configuration service which includes retrieval by key and notifications of configuration updates/deletes.
A test system chaincode was created for this test and added to the test peer image.
closes #246
> test: Added ledger configuration service BDD test

- pkg/config/ledgerconfig/config/criteria.go
- pkg/config/ledgerconfig/config/criteria_test.go
- pkg/config/ledgerconfig/config/keyvalue.go
- pkg/config/ledgerconfig/mgr/querymgr_test.go
- pkg/config/ledgerconfig/mgr/updatemgr_test.go
- Changed the error message to 'field [AppName] is required'
- Also, omitted empty fields in Criteria and Key for marshalled JSON
closes #252
> fix: Ambiguous error message 'field [Name] is required'

- pkg/config/ledgerconfig/mgr/querymgr.go
- pkg/config/ledgerconfig/mgr/querymgr_test.go
When a search is performed using criteria that is deemed to be 'complete' then the retrieval is performed by key as opposed to by indexed query.
In the case where applications have components, and an AppName and AppVersion were provided, then only a key-based retrieval was performed. This resulted in the key not being found.
This patch modifies the behavior by also performing an index-based query if the key retrieval resulted in nil.
closes #251
> fix: No match for query if criteria is 'unique'

- pkg/common/common.go
- pkg/common/common_test.go
When converting from time.Time to timestamp.Timestamp, the current time was always being used.
closes #261
> fix: Error converting to Timestamp

- mod/peer/gossip/api/gossipapi.go
- pkg/common/blockvisitor/blockvisitor.go
- pkg/common/blockvisitor/blockvisitor_test.go
- pkg/gossip/blockpublisher/blockpublisher.go
- pkg/gossip/blockpublisher/blockpublisher_test.go
Added a BlockVisitor that is synchronous and has the capability of (1) returning errors to the caller and (2) stopping traversal as soon as an error occurs.
The existing BlockPublisher was refactored to use the BlockVisitor to traverse the block.
closes #263
> feat: Implement BlockVisitor

- go.mod
- go.sum
- mod/peer/collections/policy/validator_test.go
- mod/peer/go.mod
- mod/peer/go.sum
- pkg/collections/offledger/dissemination/disseminator.go
- pkg/collections/offledger/dissemination/disseminator_test.go
- pkg/collections/offledger/policy/validator.go
- pkg/collections/offledger/policy/validator_test.go
- scripts/pull_fabric.sh
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
This patch ensures that off-ledger (and DCAS) data are not automatically pushed (disseminated) to all committers but are pushed to the number of committers specified by MaximumPeerCount in the collection policy. If MaximumPeerCount is greater than the number of committers then additional endorsers are selected.
Also, RequiredPeerCount/MaximumPeerCount are not required to be greater than 0. In some situations you may just want to store the data to the local peer. Although, if MaximumPeerCount is set to 0 but the local peer is not a committer then a random committer is chosen to which to disseminate.
close #266
> fix: Off-ledger collection data should not be pushed to all committers

- pkg/collections/client/client.go
- pkg/collections/client/client_test.go
- pkg/collections/offledger/dcas/client/dcasclient.go
- pkg/collections/offledger/dcas/client/dcasclient_test.go
- test/bddtests/bddtests_test.go
Return an error from New if the ledger is nil for the given channel.
closes #272
> fix: Panic in off-ledger client when channel not joined

- ci/azure-pipelines.yml
- mod/peer/resource/resource.go
- mod/peer/resource/resource_test.go
- pkg/resource/resourcemgr.go
- pkg/resource/resourcemgr_test.go
Added a mechanism to provide dependencies to resources on peer startup and when joining a channel. The peer manages the lifecycle of the resource as follows:
- New(dependencies...) - Create a new instance of the resource where the peer provides all of the declared dependencies
- ChannelJoined(channelID) - Called when a peer joins a channel
- Close - Called when the peer is shut down
closes #259
> feat: System managed resources with dependency injection

- mod/peer/endorser/endorser.go
- mod/peer/endorser/endorser_test.go
- mod/peer/gossip/dispatcher/dispatcher.go
- mod/peer/gossip/dispatcher/dispatcher_test.go
- pkg/endorser/endorser.go
- pkg/endorser/endorser_test.go
- pkg/gossip/dispatcher/dispatcher.go
- pkg/gossip/dispatcher/dispatcher_test.go
- pkg/gossip/dispatcher/provider.go
Added collection read/write-set filter and Gossip dispatcher provider resources which may be used as providers to other resources.
Note that the resources are not registered in this commit but will be once all resources have been converted to use dependency injection.
closes #298
> feat: Added CollRWSetFilter and Dispatcher provider resources

- go.mod
- go.sum
- mod/peer/collections/retriever/retriever.go
- mod/peer/collections/storeprovider/storeprovider.go
- mod/peer/endorser/endorser.go
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/gossip/dispatcher/dispatcher.go
- pkg/peer/init.go
- pkg/resource/resourcemgr.go
- pkg/resource/resourcemgr_test.go
- pkg/testutil/ext_test_env.go
- scripts/pull_fabric.sh
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
Enhanced the resource manager to deduce the order in which resources are registered and therefore specifying a priority is not necessary.
closes #308
> feat: Remove priority during resource registration

- cmd/chaincode/configscc/configscc.go
- cmd/chaincode/configscc/configscc_test.go
- pkg/config/ledgerconfig/config/service.go
- pkg/config/ledgerconfig/service/service.go
- pkg/config/ledgerconfig/service/service_test.go
- pkg/config/ledgerconfig/service/servicemgr.go
- pkg/peer/init.go
- pkg/peer/init_test.go
- test/scc/testscc/testscc.go
The config service is now registered as a resource and may be injected as a dependency to other resources/system chaincodes that require it.
The static function GetSvcMgr() was removed.
closes #311
> feat: Convert ledger config service to be a resource

- pkg/common/requestmgr/requestmgr.go
- pkg/gossip/dispatcher/dispatcher.go
- pkg/gossip/dispatcher/dispatcher_test.go
- test/bddtests/features/ledger_config.feature
- test/bddtests/features/off_ledger.feature
- test/bddtests/features/transient_data.feature
When a local peer does not have the off-ledger data stored then it asks for the data from other peers using Gossip. Non-endorsing committers are also being asked for the data but the non-endorser was rejecting the request. This patch changes this logic so that a committing peer will also respond with the data since all endorsers may be unavailable.
closes #327
> fix: Committer should not reject off-ledger data requests

- pkg/config/ledgerconfig/mgr/keyvaluemap.go
- pkg/config/ledgerconfig/mgr/querymgr.go
- pkg/config/ledgerconfig/mgr/querymgr_test.go
- pkg/config/ledgerconfig/service/service.go
- test/bddtests/features/ledger_config.feature
Added a 'Get' function to the query manager that will retrieve a single key via GetState instead of range query. This allows you to have configuration in an application, as well as components.
closes #345
> fix: Use GetState to retrieve config for a config key

- cmd/chaincode/configcc/configcc.go
- cmd/chaincode/configcc/configcc_test.go
- pkg/config/ledgerconfig/config/service.go
- pkg/config/ledgerconfig/mgr/querymgr_test.go
- pkg/config/ledgerconfig/mgr/updatemgr.go
- pkg/config/ledgerconfig/mgr/updatemgr_test.go
- pkg/config/ledgerconfig/mocks/validator.gen.go
- pkg/config/ledgerconfig/service/service_test.go
- pkg/config/ledgerconfig/validator/validator.go
- pkg/config/ledgerconfig/validator/validator_test.go
Removed the CanValidate function. All validators will be invoked for every config update.
closes #364
> refactor: Refactor the config validator interface

- pkg/config/ledgerconfig/config/config.go
- pkg/config/ledgerconfig/config/keyvalue.go
- pkg/config/ledgerconfig/config/keyvalue_test.go
- pkg/config/ledgerconfig/mgr/keyvaluemap.go
- pkg/config/ledgerconfig/mgr/updatemgr_test.go
- test/bddtests/config_steps.go
- test/bddtests/features/ledger_config.feature
The 'Tags' field was added to a config value so that config validators may differentiate between config types that they are capable of validating.
closes #365
> feat: Added a 'Tags' field to the config value

- ci/azure-pipelines.yml
- pkg/common/blockvisitor/blockvisitor.go
- pkg/common/blockvisitor/blockvisitor_test.go
- pkg/common/blockvisitor/context.go
- pkg/common/blockvisitor/context_test.go
- pkg/gossip/blockpublisher/blockpublisher.go
Clients may add a custom error handler to the block visitor which may handle the error by indicating whether further processing of the block should be halted.
closes #374
> feat: Add error handler to block visitor

- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore.go
- test/bddtests/features/off_ledger.feature
An expiry time of 0 indicates that the data should never be purged. The CouchDB query was modified to exclude those documents.
closes #373
> fix: Don't purge off-ledger data whose expiry is set to 0

- pkg/collections/offledger/dissemination/disseminationplan.go
- pkg/collections/offledger/dissemination/disseminator_test.go
- pkg/collections/offledger/dissemination/localmspprovider.go
- pkg/collections/offledger/dissemination/localmspprovider_test.go
- pkg/collections/offledger/storeprovider/olstore.go
- pkg/common/implicitpolicy/implicitcollpolicy.go
- pkg/common/implicitpolicy/implicitcollpolicy_test.go
- pkg/common/support/collconfigretriever.go
- pkg/common/support/collconfigretriever_test.go
- pkg/endorser/endorser_test.go
- pkg/gossip/dispatcher/dispatcher_test.go
- pkg/peer/init.go
- test/bddtests/features/off_ledger.feature
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
An implicit-org collection policy is defined as ORG('IMPLICIT-ORG.member'), which indicates that data for the collection are stored and distributed only within the peer's local org.
closes #377
> feat: Add 'implicit org' policy for off-ledger collections

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- mod/peer/gossip/state/state.go
- mod/peer/gossip/state/state_test.go
- test/bddtests/fixtures/docker-compose.yml
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
When a non-committing peer receives an unvalidated block, it is ignored before it is added to the payload buffer. Otherwise a mismatch results between the peer's current block number and the payload buffer's sequence number, and subsequent blocks are rejected.
closes #388
> fix: Ignore unvalidated blocks from Gossip at non-committing peer

- go.mod
- pkg/common/blockvisitor/blockvisitor.go
- pkg/common/blockvisitor/blockvisitor_test.go
Added a Cause() function to visitorError so that a client can use errors.Cause() to extract the cause of the error.
closes #391
> feat: Add Cause to visitorError

- pkg/collections/offledger/dissemination/disseminator.go
- pkg/collections/offledger/dissemination/disseminator_test.go
- pkg/collections/offledger/retriever/olretriever.go
- pkg/collections/offledger/retriever/olretriever_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/roles/roles.go
- pkg/roles/roles_test.go
- test/bddtests/fixtures/docker-compose-base.yml
- test/bddtests/fixtures/docker-compose.yml
If a peer does not have the off-ledger data stored locally then multiple sets of peers are asked for the data until a configurable maximum number of attempts is reached or no more peers are left (that haven't already been attempted).
The peer selection algorithm has also been optimized in the case of clustered peer configuration. If the peers are clustered then only peers in other orgs are asked for the data (since all peers in the same org share the same database).
closes #396
> feat: Retry off-ledger data retrieval

- go.mod
- mod/peer/go.mod
- pkg/collections/offledger/dissemination/disseminator.go
- pkg/collections/offledger/dissemination/disseminator_test.go
- pkg/collections/offledger/storeprovider/olstore.go
- pkg/collections/offledger/storeprovider/olstore_test.go
- pkg/collections/offledger/storeprovider/store/couchdbstore/dbstore.go
- pkg/collections/storeprovider/store.go
- pkg/collections/storeprovider/storeprovider_test.go
- test/bddtests/features/off_ledger.feature
In the special case where the collection policy specifies 0 for MaximumPeers, the data is not disseminated to a committing peer, but the data is persisted directly by the non-committing peer.
closes #399
> feat: Allow non-committing peers to persist off-ledger data

- go.mod
- mod/peer/go.mod
- pkg/txn/api/api.go
- pkg/txn/api/service.go
- pkg/txn/handler/checkforcommit.go
- pkg/txn/handler/preendorsed.go
- pkg/txn/handler/preendorsed_test.go
- pkg/txn/service.go
- pkg/txn/service_test.go
- test/bddtests/features/step_definitions/txn_steps.js
- test/bddtests/features/txn.feature
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/txn_steps.go
- test/handler/exampleauthfilter/exampleauthfilter.go
The CommitEndorsements function accepts a set of signed endorsements from the client and sends the endorsements to the orderer.
closes #407
> feat: Added CommitEndorsements to Txn service

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- pkg/chaincode/scc/scc.go
- pkg/chaincode/scc/scc_test.go
- test/bddtests/features/ledger_config.feature
- test/bddtests/features/txn.feature
- test/bddtests/fixtures/config/fabric/core.yaml
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
- test/bddtests/fixtures/fabric/peer/cmd/main.go
- test/cc/testscc/testscc.go
Updated to the latest fabric-mod which adds ext system chaincodes to the build-in list, allowing them to be invoked.
Also added support for ChannelJoined on ext SCC so that it may be informed when a channel is joined (since Init is no
longer called on system chaincodes).
closes #425
> fix: Support Invoke and ChannelJoined for system chaincode

- mod/peer/gossip/api/gossipapi.go
- mod/peer/gossip/mocks/blockpublisher.go
- pkg/common/blockvisitor/blockvisitor.go
- pkg/common/blockvisitor/blockvisitor_test.go
- pkg/common/blockvisitor/context.go
- pkg/gossip/blockpublisher/blockpublisher.go
- pkg/gossip/blockpublisher/blockpublisher_test.go
- pkg/mocks/mockblockbuilder.go
- pkg/mocks/mockblockhandler.go
- pkg/mocks/mockblockpublisher.go
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
Clients can now register for collection hash read and write block events.
closes #431
> feat: Support for collection hash r/w sets in block publisher

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- test/bddtests/features/e2e.feature
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
Updated to latest fabric-mod which fixes the issue of stale collection hash cache entries.
closes #463
> fix: Delete collection hash entries from cache on update

- pkg/chaincode/notifier/notifier.go
> fix: Call Done() on query executor in CC notifier

- go.mod
- go.sum
- mod/peer/go.mod
- mod/peer/go.sum
- test/bddtests/fixtures/fabric/peer/cmd/go.mod
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
This update fixes the issue, when the state cache is enabled, we intermittently see the error:
- private data matching public hash version is not available. Public hash version = {BlockNum: 101, TxNum: 1}, Private data version = {BlockNum: 94, TxNum: 0}
closes #507
> chore: Update to latest fabric-mod

- mod/peer/endorser/api/endorser.go
- pkg/config/ledgerconfig/service/service_test.go
- pkg/config/ledgerconfig/service/servicemgr.go
- pkg/config/ledgerconfig/state/kvresultsiter.go
- pkg/config/ledgerconfig/state/qestateretriever.go
- pkg/config/ledgerconfig/state/qestateretriever_test.go
- pkg/txn/proprespvalidator/validator_test.go
During an endorsement if a chaincode invokes the ledger config service then an intermittent deadlock results. The scenario is as follows:
- Chaincode is invoked so a ledger read lock is acquired
- Block is being committed so a write lock on the ledger is attempted. This call blocks until the read lock is released.
- Chaincode invokes ledger config service which invokes NewQueryExecutor on the ledger. This function attempts to acquire a read lock and therefore a deadlock occurs.
This fix uses the state database provider instead of the query executor to retrieve ledger configuration so that a ledger lock is not required.
closes #515
> fix: Deadlock in ledger config

- go.mod
- go.sum
- pkg/collections/offledger/storeprovider/olstore.go
- pkg/collections/offledger/storeprovider/olstore_test.go
- pkg/collections/offledger/storeprovider/olstoreprovider.go
- pkg/collections/offledger/storeprovider/olstoreprovider_test.go
- pkg/collections/storeprovider/storeprovider.go
- pkg/collections/storeprovider/storeprovider_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/mocks/mockrwsetbuilder.go
- test/bddtests/features/lc_off_ledger.feature
- test/bddtests/features/off_ledger.feature
- test/bddtests/go.mod
- test/bddtests/go.sum
Off-ledger collections cannot reliably cache data since updates to a key may not be propagated to all peers and a subsequent Get may retrieve stale data from the cache. Although, DCAS collections can reliably cache data, since an update to a DCAS value will always result in the same value. Deletes are still a problem since a DCAS value may still be cached on one or more peers. Support for delete of a DCAS key should be deprecated.
This commit (by default) enables the cache for DCAS collection types and disables the cache for off-ledger collection types. (Note that the cache may still be disabled for DCAS collection types by setting the off-ledger cache size to 0.)
This commit also updates to the latest fabric-sdk-go.
closes #382
> fix: Enable cache for DCAS collections

- go.mod
- go.sum
- mod/peer/go.sum
- pkg/collections/transientdata/dissemination/disseminator.go
- pkg/collections/transientdata/dissemination/disseminator_test.go
- pkg/collections/transientdata/retriever/transientdataretriever.go
- pkg/collections/transientdata/retriever/transientdataretriever_test.go
- test/bddtests/features/lc_transient_data.feature
- test/bddtests/features/transient_data.feature
- test/bddtests/fixtures/fabric/peer/cmd/go.sum
- test/bddtests/fixtures/fabric/v1.4/config/configtx.yaml
- test/bddtests/fixtures/fabric/v2.2/config/configtx.yaml
- test/bddtests/go.mod
- test/bddtests/go.sum
A deterministic algorithm is used to select a set of orgs and peers within those orgs to which to disseminate transient data. The same algorithm is then used to select the peers from which to retrieve the data. The algorithm is based on using a modulus operator on the hash of the key and the length of the set of orgs and peers within the orgs. If the length of the set of orgs or peers within the orgs changes between the time the data was disseminated and the time it is retrieved then (most likely) one or more peers that do not have the data could be selected.
This commit adds a fallback mechanism such that, if none of the selected peers has the data, then an attempt is made to retrieve the data from the remaining set of peers within each of the orgs that are selected (based on the key …
> fix: Retrieve from other peers if transient data not found

- pkg/collections/transientdata/storeprovider/store/cache/cache.go
- pkg/collections/transientdata/storeprovider/store/cache/cache_test.go
- pkg/collections/transientdata/storeprovider/tdstore.go
- pkg/collections/transientdata/storeprovider/tdstore_test.go
- pkg/collections/transientdata/storeprovider/tdstoreprovider.go
- pkg/config/config.go
- pkg/config/config_test.go
- test/bddtests/features/lc_transient_data.feature
- test/bddtests/features/transient_data.feature
Previously transient data was only stored in memory unless the maximum cache size had been exceeded, at which time the oldest entries were offloaded to a database. This commit adds a configuration parameter to allow transient data to always be persisted (as well as cached). This way, if a peer goes down temporarily then the transient data will still be available when it comes back up.
closes #520
> feat: Added option to always persist transient data

- pkg/blkstorage/cdbblkstorage/blockcache.go
- pkg/blkstorage/cdbblkstorage/blockcache_test.go
Ensure that the new block height of the loaded config block is greater than the existing config block before pinning it.
closes #543
> fix: Cache config block only if newer

- pkg/pvtdatastorage/cachedpvtdatastore/store_impl.go
- pkg/pvtdatastorage/cachedpvtdatastore/store_impl_test.go
- pkg/pvtdatastorage/cdbpvtdatastore/store_impl.go
- pkg/pvtdatastorage/cdbpvtdatastore/store_impl_test.go
The couch DB private storage and the cached private storage may result in race condition when updating/reading the member variables: isEmpty and lastCommittedBlock. This fix ensures any reads/updates are performed using atomic functions.
closes #548
> fix: Race condition in Couch DB private data store

- mod/peer/gossip/api/gossipapi.go
- pkg/common/blockvisitor/blockvisitor.go
- pkg/common/blockvisitor/blockvisitor_test.go
- pkg/common/blockvisitor/context.go
- pkg/gossip/blockpublisher/blockpublisher.go
- pkg/gossip/blockpublisher/blockpublisher_test.go
- pkg/mocks/mockblockhandler.go
- pkg/mocks/mockblockpublisher.go
Clients may now register to handle entire published blocks.
closes #552
> feat: Added block handler to Block Publisher

- pkg/pvtdatastorage/cachedpvtdatastore/store_impl.go
- pkg/pvtdatastorage/cdbpvtdatastore/store_impl.go
- pkg/pvtdatastorage/cdbpvtdatastore/test_exports.go
- pkg/pvtdatastorage/common/api.go
- pkg/pvtdatastorage/store_impl.go
- pkg/pvtdatastorage/store_impl_test.go
When a non-committing peer receives a Gossip request for private data for a specific block it would return an error that the last committed block was not at the desired height. This was because the 'lastCommittedBlockNum' is cached and only updated in the Commit function. Since Commit is never called on a non-committing peer, the value for 'lastCommittedBlockNum' was stuck at the value it was set to when the peer was started.
This commit registers a block handler with the Block Publisher in the CouchDB private data store to update 'lastCommittedBlockNum' when it receives a published block.
closes #547
> fix: Non-committing peer returns error when handling private data state request

- pkg/gossip/appdata/handlerregistry.go
- pkg/gossip/appdata/handlerregistry_test.go
- pkg/gossip/appdata/retriever.go
- pkg/gossip/dispatcher/dispatcher.go
- pkg/gossip/dispatcher/dispatcher_test.go
- pkg/gossip/state/cacheupdater_test.go
- pkg/gossip/state/stateupdate.go
- test/cc/hellocc/hellocc.go
The reqponses for app-data requests are now asynchronous. The request handler is provided a 'responder' to which the handler may respond immediately or in the (near) future.
closes #550
> refactor: Asynchronous Gossip app-data request handler

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/roles/roles.go
- pkg/roles/roles_test.go
- pkg/validation/validationpolicy/mocks/mockpolicyevaluator.go
- pkg/validation/validationpolicy/peergroups.go
- pkg/validation/validationpolicy/peergroups_test.go
- pkg/validation/validationpolicy/peergroupselector.go
- pkg/validation/validationpolicy/peergroupselector_test.go
- pkg/validation/validationpolicy/policyevaluator.go
- pkg/validation/validationpolicy/policyevaluator_test.go
- pkg/validation/validationresults/validationresults.go
- pkg/validation/validationresults/validationresults_test.go
Defined a validation policy and implemented a policy evaluator that selects the peers that should validate transactions within a block. The policy evaluator also validates validation results according to the policy.
closes #556
> feat: Validation Policy
